### ISSUE TITLE
Updating document - 'Received RST_STREAM with code 1'

### ISSUE THREAD

**Issue by ryan-saffer** [firebase/firebase-admin-node#2345]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Google Cloud Function Runtime (Gen 2) Node 18
  * Firebase SDK version: 11.11.0
  * Firebase Product: Firestore
  * Node.js version: 18.18
  * NPM version: 9.8.1

### [REQUIRED] Step 3: Describe the problem
Randomly receive error when updating a firestore document:
```'13 INTERNAL: Received RST_STREAM with code 1'```

#### Steps to reproduce:

I am seeing the error occur randomly when using `ref.set(data, { merge: true })`

#### Relevant Code:

```typescript
const firestore = getFirestore()
firestore.setting({ ignoreUndefinedProperties: true })

const id = // existing document id
const newData = { foo: 'bar' }
try {
  await  firestore.collection('bookings').doc(id).set(newData, { merge: true })
} catch(error) {
  console.log(error.message) // '13 INTERNAL: Received RST_STREAM with code 1'
}
```

**Comment by wagerlab** [comment]
We're seeing this same issue on firestore batch commit() calls as well

**Comment by ryan-saffer** [comment]
This issue was being caused due to an error on my end.

My cloud function was being used as a webhook, and the first thing I did was `res.status(200). send()` to tell the webhook that I received the request.

It looks like by doing this, it tells the runtime it is safe to teardown the instance, and by the time I updated my database, the connection was closed.

This function has been doing this for years without any issues, however the issue began appearing while using the new Gen 2 cloud functions, so it seems the new runtime tears down the instance faster.

I resolved this by publishing my data to a pubsub, and then returning a 200 to the webhook.

@wagerlab I am closing this issue due to it being my mistake - perhaps raise a new issue with your error.

**Comment by maylorsan** [comment]
@wagerlab Any updates?We have same issue with `.update(fieldsToUpdate);` method

**Comment by narenpublic** [comment]
I have been seeing this issue since Oct 16 as well.

**Comment by Jamesfleming1** [comment]
I am seeing this as well. Redeploying my functions temporarily fixes them, and then they break again

**Comment by im12345dev** [comment]
As well here, using GCP Cloud Run, any solutions?

**Comment by ciriousjoker** [comment]
Happens for us since 9th Oct 2023 as well.

- In our case, we await the `.set()` call that fails, so the above mentioned issue of teardown shouldn't occur at all.
- I thought this was because of a function timeout, but the function only ran for 10 seconds when the error occurred

**Comment by maylorsan** [comment]
We haven't found a solution to this issue yet.

We've attempted several methods, but none have resolved the problem:

- Switched the update method to use set and set with {merge: true}, but this didn't work.
- Created a new cloud function dedicated solely to this method. Surprisingly, it didn't work either. However, it's noteworthy that we have several other cloud functions that update user data using the same method, and they function as expected.
What's even more perplexing is that this issue arises in about 60% of our http cloud function calls, and it seems to occur randomly. We haven't been able to identify a consistent pattern.

Interestingly, everything operates flawlessly in our development project. The only difference is that the development project has a smaller User collection.

I'm starting to suspect that this might be related to some undocumented limitation in Firestore...

@ryan-saffer can we reopen this issue?

**Comment by ryan-saffer** [comment]
Given many people are reporting the same problem I am reopening issue.

**Comment by CollinsVizion35** [comment]
got the same issue :

at WriteBatch.commit 
    at DocumentReference.set 

    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 13,
  details: 'Received RST_STREAM with code 1',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} },
  note: 'Exception occurred in retry method that was not classified as transient'

**Comment by TheRealFlyingCoder** [comment]
Coming here to update, also experiencing the same error out of the blue, running a Node.js process locally on a server.

**Comment by narenpublic** [comment]
I have a node script I run locally to test and then a cloud function that runs on an interval.  Both are experiencing this issue. I send a bunch of doc(id).update(obj) calls with a bunch of promises. I've lost 24 hours to this already with no rhyme or reason.  Sometimes 100 might go through and then with the same data/call 0.  Is there any kind of rate limit with a cool off period that is buried somewhere.

This is super frustrating and vexing because my logs had nothing until Oct 16 and *after* I did a deploy of a cloud function so you would think that it had to do with the new deploy but I can't get back to functional using a local script.  Oy.

**Comment by umarmirza20** [comment]
This issue recently started happening with me today. In my cloud function I save bunch of write batches and then return a 200 success call. So it can't be that the instance is being torn down because I send a 200 success after all batches a re written. However as soon as I try to commit the batches I get this error

**Comment by fabdurso** [comment]
Same issue here.

**Comment by thomasdrouin** [comment]
Same issue for our project.

**Comment by znayer** [comment]
Same issue, huge headache.

**Comment by pc7** [comment]
Same here.

Started in all our Firebase projects at the same time, between 16:30 and 18:30 BST on 20th October, europe-west2 region.

It's not connected to any deployments from us, or changes to our code.

Functions that are failing:

 - all scheduled functions that contain Firestore deletes.

 - all trigger functions attached to Firestore document updates, that execute writes to other Firestore documents. All have 'await'.

All failing with this error:

13 INTERNAL: Received RST_STREAM with code 1

    at runNextTicks (node:internal/process/task_queues:61:5)
    at processImmediate (node:internal/timers:437:9)
    at process.topLevelDomainCallback (node:domain:161:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)"

Any help would be very much appreciated.

**Comment by raphaelolivero** [comment]
I managed to work around the issue (for now) by changing this particular unit:

```js
const promises = []
await tenantsQuerySnapshot.docs.forEach(async tenantDoc => {
  ...
  promises.push(
    pricesDocRef.set({
      DISPATCH_FEE: +dispatchFee,
      CALL_FEE: +callFee,
      PLATFORM_FEE: +platformFee,
    }, { merge: true }),
  )
})

await Promise.all(promises)

res.status(201).send('success')
```

To this:
```js
await Promise.all(tenantsQuerySnapshot.docs.map(async tenantDoc => {
  const pricesDocRef = usageDocSnapshot.ref.collection('metadata').doc('prices')
  ...

  const result = await pricesDocRef.set({
    DISPATCH_FEE: +dispatchFee,
    CALL_FEE: +callFee,
    PLATFORM_FEE: +platformFee,
  }, { merge: true })

  // For debugging purposes.
  console.debug(usageDayPath, JSON.stringify(result))
}))

res.status(201).send('success')
```

I also faced this issue using a batch.

**Comment by TheSavageDev** [comment]
Having the same issue.

**Comment by ehsannas** [comment]
Hi everyone, thanks for reporting. We have started to investigate, and will provide updates.

**Comment by mikemoone** [comment]
The issue does seem to be related to the size of the batch, so a workaround that has helped on our side is adding an automatic retry which breaks the batch into smaller chunks if the first write attempt fails:

```
  asyncWriteBatch: async (allWrites: BatchWrite[], chunkSize = 500, delay = 0) => {
    if (allWrites.length === 0) return;
    const chunks = _.chunk(allWrites, chunkSize);
    for (const chunk of chunks) {
      try {
        const batch = firestore.batch();
        for (const write of chunk) {
          switch (write.type) {
            case 'delete':
              batch.delete(write.ref);
              break;
            case 'set':
              batch.set(write.ref, write.value, write.options || {});
              break;
            case 'update':
              batch.update(write.ref, write.value);
              break;
            default:
              break;
          }
        }
        await batch.commit();
      } catch {
        await sleep(1000);
        const batch = firestore.batch();
        const subChunks = _.chunk(chunk, 10);
        for (const subChunk of subChunks) {
          for (const write of subChunk) {
            switch (write.type) {
              case 'delete':
                batch.delete(write.ref);
                break;
              case 'set':
                batch.set(write.ref, write.value, write.options || {});
                break;
              case 'update':
                batch.update(write.ref, write.value);
                break;
              default:
                break;
            }
          }
        }
        await batch.commit();
      }
      if (delay) {
        await sleep(delay);
      }
    }
  },
```

**Comment by ciriousjoker** [comment]
Did some more digging, here are my notes:
- Only affects small percentage of our calls (55 out of 1034)
- There was one set of inputs that lead to a reliable crash
- Our function is deterministic, and I've reconstructed the data passed to `.set()` (see below)
- I've since deployed a new version, which doesn't crash anymore (suggests that our code was the issue)
- I've then redeployed the original version (unfortunately not the exact same executable, since v1 cloud functions can't be rolled back). Instead, I've redeployed the code from the same day (21.06.2023). This also doesn't have the issue anymore (suggests that the code isn't the issue).
- The only interesting things about the data passed to `.set()` are these: We used `Timestamp.now()` instead of a `FieldValue` and there are lots of `DocumentReference`s

<details><summary>Stacktrace</summary>

```log
Unhandled error Error: 13 INTERNAL: Received RST_STREAM with code 1
    at callErrorFromStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /workspace/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at

Caused by: Error
    at WriteBatch.commit (/workspace/node_modules/@google-cloud/firestore/build/src/write-batch.js:433:23)
    at DocumentReference.set (/workspace/node_modules/@google-cloud/firestore/build/src/reference.js:393:27)
    at /workspace/src/functions/workoutplan/generate_workoutplan.js:55:75
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /workspace/node_modules/firebase-functions/lib/common/providers/https.js:458:26 {
  code: 13,
  details: 'Received RST_STREAM with code 1',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} },
  note: 'Exception occurred in retry method that was not classified as transient'
}
```
</details> 

<details><summary>data</summary>

```json
{
  "dateLastUpdated": {
    "_seconds": 1698086022,
    "_nanoseconds": 952000000
  },
  "days": [
    {
      "workouts": [
        {
          "name": {
            "de": "2",
            "en": "2"
          },
          "type": "B",
          "training": {
            "_firestore": {},
            "_path": {
              "segments": [
                "B",
                "2"
              ]
            },
            "_converter": {}
          }
        }
      ]
    },
    {
      "workouts": [
        {
          "name": {
            "de": "13",
            "en": "13"
          },
          "type": "A",
          "training": {
            "_firestore": {},
            "_path": {
              "segments": [
                "A",
                "13"
              ]
            },
            "_converter": {}
          }
        },
        {
          "name": {
            "de": "6",
            "en": "6"
          },
          "type": "A",
          "training": {
            "_firestore": {},
            "_path": {
              "segments": [
                "A",
                "6"
              ]
            },
            "_converter": {}
          }
        },
        {
          "name": {
            "de": "10",
            "en": "10"
          },
          "type": "A",
          "training": {
            "_firestore": {},
            "_path": {
              "segments": [
                "A",
                "10"
              ]
            },
            "_converter": {}
          }
        }
      ]
    },
    {
      "workouts": []
    },
    {
      "workouts": []
    },
    {
      "workouts": [
        {
          "name": {
            "de": "13",
            "en": "13"
          },
          "type": "A",
          "training": {
            "_firestore": {},
            "_path": {
              "segments": [
                "A",
                "13"
              ]
            },
            "_converter": {}
          }
        },
        {
          "name": {
            "de": "10",
            "en": "10"
          },
          "type": "A",
          "training": {
            "_firestore": {},
            "_path": {
              "segments": [
                "A",
                "10"
              ]
            },
            "_converter": {}
          }
        },
        {
          "name": {
            "de": "11",
            "en": "11"
          },
          "type": "A",
          "training": {
            "_firestore": {},
            "_path": {
              "segments": [
                "A",
                "11"
              ]
            },
            "_converter": {}
          }
        }
      ]
    },
    {
      "workouts": [
        {
          "name": {
            "de": "3",
            "en": "3"
          },
          "type": "B",
          "training": {
            "_firestore": {},
            "_path": {
              "segments": [
                "B",
                "3"
              ]
            },
            "_converter": {}
          }
        }
      ]
    },
    {
      "workouts": [
        {
          "name": {
            "de": "1",
            "en": "1"
          },
          "type": "B",
          "training": {
            "_firestore": {},
            "_path": {
              "segments": [
                "B",
                "1"
              ]
            },
            "_converter": {}
          }
        }
      ]
    }
  ],
  "isCustomized": false,
  "goals": [
    {
      "_firestore": {},
      "_path": {
        "segments": [
          "C",
          "some id"
        ]
      },
      "_converter": {}
    },
    {
      "_firestore": {},
      "_path": {
        "segments": [
          "C",
          "some id"
        ]
      },
      "_converter": {}
    },
    {
      "_firestore": {},
      "_path": {
        "segments": [
          "C",
          "some id"
        ]
      },
      "_converter": {}
    },
    {
      "_firestore": {},
      "_path": {
        "segments": [
          "C",
          "some id"
        ]
      },
      "_converter": {}
    }
  ],
  "trainingplans": [
    {
      "_firestore": {},
      "_path": {
        "segments": [
          "B",
          "2"
        ]
      },
      "_converter": {}
    },
    {
      "_firestore": {},
      "_path": {
        "segments": [
          "B",
          "1"
        ]
      },
      "_converter": {}
    },
    {
      "_firestore": {},
      "_path": {
        "segments": [
          "B",
          "3"
        ]
      },
      "_converter": {}
    }
  ],
  "skills": [
    {
      "_firestore": {},
      "_path": {
        "segments": [
          "A",
          "13"
        ]
      },
      "_converter": {}
    },
    {
      "_firestore": {},
      "_path": {
        "segments": [
          "A",
          "10"
        ]
      },
      "_converter": {}
    },
    {
      "_firestore": {},
      "_path": {
        "segments": [
          "A",
          "6"
        ]
      },
      "_converter": {}
    },
    {
      "_firestore": {},
      "_path": {
        "segments": [
          "A",
          "11"
        ]
      },
      "_converter": {}
    }
  ]
}
```
</details>

**Comment by edmilsonss** [comment]
I had the same problem since last friday and so far I understood looks like something inside firebase / grpc implementation related to long time delays between firebase calls.

Also, correct me if I'm wrong, firebase library seems to be moving away from gRPC but it still keeps it as a default option if you don't set `preferRest: true` ([see docs](https://firebase.google.com/docs/reference/admin/node/firebase-admin.firestore.firestoresettings))

For me the solution was calling init right before performing an operation and/or changing firebase config to prefer using rest comunication.

Here is my code snipet:

```
function getFbDb() {
  const mainFirebaseApp = firebaseAdmin.initializeApp({
      credential: firebaseAdmin.credential.applicationDefault()
    }, uuid.v4());

  const db = mainFirebaseApp.firestore();
  const settings = {
    preferRest: true,
    timestampsInSnapshots: true
  };
  db.settings(settings);
  return { db, firebaseApp: mainFirebaseApp };
}
const { db, firebaseApp } = getFbDb();
```

Use const `{ db, firebaseApp } = getFbDb();` everytime you have to execute an operation.

Another _"dirty option"_ seems to be using a retry approach after the first fail. I'd use this only in an emergency situation.

**Comment by narenpublic** [comment]
@edmilsonss thank you so much.  I modified my data service

`  db: FirebaseFirestore.Firestore;
  constructor(db: FirebaseFirestore.Firestore) {
    this.db = db;
    const settings = {
      preferRest: true,
      timestampsInSnapshots: true
    };
    this.db.settings(settings);
  }`
  
  And now when I send big bunches of promises for doc.update() they are all succeeding.

**Comment by sourabh-joshi** [comment]
> I had the same problem since last friday and so far I understood looks like something inside firebase / grpc implementation related to long time delays between firebase calls.
> 
> Also, correct me if I'm wrong, firebase library seems to be moving away from gRPC but it still keeps it as a default option if you don't set `preferRest: true` ([see docs](https://firebase.google.com/docs/reference/admin/node/firebase-admin.firestore.firestoresettings))
> 
> For me the solution was calling init right before performing an operation and/or changing firebase config to prefer using rest comunication.
> 
> Here is my code snipet:
> 
> ```
> function getFbDb() {
>   const mainFirebaseApp = firebaseAdmin.initializeApp({
>       credential: firebaseAdmin.credential.applicationDefault()
>     }, uuid.v4());
> 
>   const db = mainFirebaseApp.firestore();
>   const settings = {
>     preferRest: true,
>     timestampsInSnapshots: true
>   };
>   db.settings(settings);
>   return { db, firebaseApp: mainFirebaseApp };
> }
> const { db, firebaseApp } = getFbDb();
> ```
> 
> Use const `{ db, firebaseApp } = getFbDb();` everytime you have to execute an operation.
> 
> Another _"dirty option"_ seems to be using a retry approach after the first fail. I'd use this only in an emergency situation.

Had to go with the dirty option :) Will try the solution you mentioned now.

**Comment by CollinsVizion35** [comment]
Thanks a lot, it think it works

former code:
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "https://papispredictor.firestore.googleapis.com",
});

// Create a Firestore instance
const db = admin.firestore();

new code:
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "https://projectname.firestore.googleapis.com",
});

// Create a Firestore instance
const db = admin.firestore();
const settings = {
  preferRest: true,
  timestampsInSnapshots: true
};
db.settings(settings);

**Comment by oyvindholmstad** [comment]
We are experiencing the same issue. The error happens both when doing many sequential updates with `await Promise.all`, and when using `batch.commit`.

Two examples:
* when running batches of updates to a set of documents (in our case, up to 40 000 changed documents) with 500 documents changed in each batch.
* when using `await Promise.all` on a set of promises.

The first one could probably be improvde by applying the dirty fix mention here, with the a retrying in smaller batches, but the second one could not be split any more.

I don't dare to change a fundamental setting as `preferRest: true` on our production database.

**Comment by maylorsan** [comment]
Hello everyone! 🚀

After spending 48 hours without sleep, we've finally nailed down an issue:

Bug Discovery and Solution 🐛
We found a bug and managed to fix it by optimizing the logic between our Firebase calls. Oddly enough, it appears that the two Firebase calls in our service, where we retrieve data followed by some intense algorithmic logic to update Firebase, were the culprits.

### Here's a snippet of the problematic code:

```
const [globalVariables, data, filtrationInfo, sortingInfo] = await Promise.all([
    getGlobalVariables(),
    database.getDataCollectionList({
      queriesAnd: [
        { field: 'is_active', filter: '==', value: true },
        { field: 'profile_lang', filter: '==', value: client?.app_lang ?? 'uk' },
        { field: 'is_public', filter: '==', value: true },
      ],
    }),
    database.getOnBoardingFiltrationInfo(),
    database.getOnBoardingSortingInfo(),
  ]);

// The recommendation creation process here was quite time-consuming, taking about 7 seconds.
const specialistsRecommendationObject = createRecommendationObject({
    client,
    filtrationInfo,
    sortingInfo,
    data,
    globalVariables,
    filtrationEnabled,
});

// We encountered an error during this update process.
await database.updateUserByID(client.id, {
    specialist_order: clientSpecialistOrder,
});
```

We successfully reduced our recommendation algorithm's runtime to 2.5 seconds, and the error in updateUserByID was resolved.

### Insights 🧠
It seems that @edmilsonss's hypothesis was on point:

"There might be issues inside the Firebase/GRPC implementation related to long time delays between Firebase calls."

Although we haven't yet experimented with preferRest: true, it's sounding like a potential solution.

Huge thanks to @edmilsonss for the insight! ❤️

**Comment by maylorsan** [comment]
> something inside firebase / grpc implementation related to long time delays between firebase calls.

**Comment by maylorsan** [comment]
Hello everyone! 🚀

We've finally nailed down an issue:

### Bug Discovery and Solution 🐛
We found a bug and managed to fix it by optimizing the logic between our Firebase calls. Oddly enough, it appears that the two Firebase calls in our service, where we retrieve data followed by some intense algorithmic logic to update Firebase, were the culprits.

Here's a snippet of the problematic code:

const [gv data, info1, info2] = await Promise.all([
    getGV(),
    database.getDataCollectionList(),
    database.getInfo1(),
    database.getInfo2(),
  ]);

// The recommendation creation process here was quite time-consuming, taking about 7 seconds.
const recommendationObject = createRecommendationObject({
    client,
    info1,
    info2,
    data,
    gv
});

// ... some other not async code

// We encountered an error during this update process.
await database.updateDocumentByID(documentID, {
    order,
});
We successfully reduced our recommendation algorithm's runtime to 2.5 seconds, and the error in updateDocumentByID was resolved.

### Insights 🧠
It seems that @edmilsonss's hypothesis was on point:

"something inside firebase / grpc implementation related to long time delays between firebase calls."

Although we haven't yet experimented with preferRest: true, it's sounding like a potential solution.

Huge thanks to @edmilsonss for the insight! ❤️

**Comment by im12345dev** [comment]
Quick update from our part, it seems to be correct what was reported here, if there is a gap (in our case due to intensive algorithm) between update/set calls it will result in the RST_STREAM error.

I can confirm that `preferRest: true` seems to resolve the issue completely for us, we have deployed our Cloud Run revision with it and so far in the last 24 hours we have received 0 errors where previously we would have received dozens by now.

Thank you @edmilsonss you saved me days of work and debugging :)

**Comment by gbourne1** [comment]
Same issue here. Until about 4 days ago everything was working fine. I am cautious about the preferRest since it might cause other unknown issues. I used it a year ago and it seemed to cause other Firestore failures. The best path is fixing the issue that appears on the 20th.

**Comment by umarmirza20** [comment]
@maylorsan what do I need to do to fix this? Update my firebase-admin library? I'm still seeing this issue today

**Comment by jobweegink** [comment]
Same here, i've been running the same cloud functions for over a few years, some of them not updated recently and this error came out of the blue.
This must be some backend thing at gcloud i suppose?

**Comment by ehsannas** [comment]
Hi everyone, thank you for your patience. Just a quick update:

We are still investigating this issue. We have got a number of different teams involved internally to help investigate different parts of the system as well as our dependencies (e.g. grpc).

In the meantime, feel free to experiment using using the `preferRest` option documented [here](https://firebase.google.com/docs/reference/admin/node/firebase-admin.firestore.firestoresettings.md#firestoresettingspreferrest). This option forces the SDK to use HTTP/1.1 REST transport rather than gRPC.

**Comment by ehsannas** [comment]
@TheRealFlyingCoder @narenpublic @jobweegink Are you able to reproduce the issue consistently locally? Would you be able to share the code you're running?

**Comment by TheRealFlyingCoder** [comment]
> @TheRealFlyingCoder @narenpublic @jobweegink Are you able to reproduce the issue consistently locally? Would you be able to share the code you're running?

No reproduction from me sorry, I only noticed it after an unusually large set of updates, and haven't had it happen again

**Comment by narenpublic** [comment]
> @TheRealFlyingCoder @narenpublic @jobweegink Are you able to reproduce the issue consistently locally? Would you be able to share the code you're running?

I just removed the preferRest and shockingly didn't see any errors passing 500+ promises to doc(id).update(). Ran it 3 times and no issues. Not sure what that means. Did you deploy some fix already?

**Comment by edmilsonss** [comment]
@narenpublic / @TheRealFlyingCoder / @ehsannas, the problem for me and for some other guys seems to happen when we do a big read, pause for some time (more than 2 minutes in my case) and then we try to write something using the same firebase app instance.

**Comment by mecclesgoogle** [comment]
What Node.JS version are people using? OP mentioned 18.8 and we are curious what version others experienced this problem on. 

If you are using GCF, you can see the major Node.JS version in the "Runtime" dropdown list in the Code Editor.

If you are running on a server, run `node --version`

**Comment by mecclesgoogle** [comment]
More specifically, what version of nghttp2 do you have?

https://github.com/nghttp2/nghttp2/releases has made some changes recently that are possible suspects.

You can get the version from npm by running `npm list nghttp2` or by printing out the value of `process.versions ` (see npm list nghttp2)

**Comment by jobweegink** [comment]
> @TheRealFlyingCoder @narenpublic @jobweegink Are you able to reproduce the issue consistently locally? Would you be able to share the code you're running?

I'm indeed able to reproduce it 100% of all the local executions, deployed it goes well for some reason.
Check the code below.

```
    async insertRecords(tenantID: string, moduleID: string, records: any[]): Promise<string[]>{
        const result: string[] = [];
        const batches: Promise<FirebaseFirestore.WriteResult[]>[] = []
        let batchCounter: number = 0
        let batch: FirebaseFirestore.WriteBatch = db.batch();

        records.forEach(record => {

            batchCounter += 1
            const recordRef: FirebaseFirestore.DocumentReference = this.getRecordRef(tenantID, moduleID, record.ID);
            record.ID = recordRef.id;
            result.push(record.ID)
            // console.log("Adding module update query for record : " + moduleRecord.ID);
            batch.set(recordRef, record, { merge: true });
            if (batchCounter === AppConstraints.MAX_QUERY_LIMIT_PER_BATCH_QUERY) {
                console.log("Commiting batch query with " + AppConstraints.MAX_QUERY_LIMIT_PER_BATCH_QUERY + " records");
                batches.push(batch.commit());
                batch = db.batch();
                batchCounter = 0;
            }
        });

        if (batchCounter > 0) {
            batches.push(batch.commit());
        }

        await Promise.all(batches);
        console.log("Commited batch queries for records: ");
        return result;
    }
```

**Comment by oyvindholmstad** [comment]
We are currently on:
* Node 16.
* firebase-admin: 11.3.0
* firebase-functions: 4.4.0

We don't use nghttp2, so I don't understand how that can be relevant.

I have been digging in our logs, and the first instance I can see of `RST_STREAM with code 1 ` is from 9. October.

**Comment by DaniyalCuboid19** [comment]
> What Node.JS version are people using? OP mentioned 18.8 and we are curious what version others experienced this problem on.
> 
> If you are using GCF, you can see the major Node.JS version in the "Runtime" dropdown list in the Code Editor.
> 
> If you are running on a server, run `node --version`
Using GCP Pubsub
- Node  : 18 
-  firebase-admin : ^11.11.0",
- firebase-functions: "^4.4.1"

**Comment by petrvecera** [comment]
In our function the error started happening ~5 days ago - no new deployment to any of our functions. 

Happens on `batch.commit()`

Functions Gen 1, Node 16
```
"firebase-admin": "11.11.0",
"firebase-functions": "4.4.1",
```

Our code is extremely simple:
```javascript
 let batch = db.batch();
  const chunkedData = chunk(matches, 499);
  for (const chunk of chunkedData) {
    for (const match of chunk) {
      const docRef = getMatchDocRef(match.id);
      batch.set(docRef, match);
    }

    await batch.commit();
    logger.info(`Saving batch of ${chunk.length} matches to the DB.`);
    batch = db.batch();
  }
```

**Comment by edmilsonss** [comment]
> What Node.JS version are people using? OP mentioned 18.8 and we are curious what version others experienced this problem on.
> 
> If you are using GCF, you can see the major Node.JS version in the "Runtime" dropdown list in the Code Editor.
> 
> If you are running on a server, run `node --version`

Node 16.
firebase-admin: 11.11.0,

**Comment by zzpreneur** [comment]
Hi, I've been experiencing this issue as well. I noticed it on 10/21/23. I'm running 

- 1st gen cloud functions
- Node 16
- "firebase-admin": "^11.3.0",
- "firebase-functions": "^4.2.1"

I pushed the fix using `{preferRest: true, timestampsInSnapshots: true}` and it fixed the main error in this thread. But now I'm seeing other errors I wasn't before this change:

```
FetchError: request to https://firestore.googleapis.com/v1/projects/PROJECT-NAME-HERE/databases/(default)/documents:runQuery?$alt=json%3Benum-encoding=int failed, reason: socket hang up"
```
Couple questions:
1. Is this issue only happening on 1st gen cloud functions? If so, does it make sense to upgrade to gen 2?
2. Any insight on the error above?

Thanks

**Comment by atomassoni** [comment]
All the affected functions are deployed on Node 18 for us. 
    "firebase-admin": "^11.10.1",
    "firebase-functions": "^4.4.1",

**Comment by jessp01** [comment]
Hi @ehsannas ,

Any news on this? If anything, this seems to happen more and more frequently in the past two days.

Thanks,

**Comment by jessp01** [comment]
Also, @ehsannas , may I ask why this issue is not reflected in https://status.cloud.google.com/?

**Comment by adamkoch** [comment]
Seeing this as well, starting a week or so back.

Node 16, Gen 1 functions:
```
    "@google-cloud/firestore": "^6.8.0",
    "firebase-admin": "^11.11.0",
    "firebase-functions": "^4.4.1",
```

Ditto to @zzpreneur - added `preferRest: true` to workaround which seems to have helped but now seeing `failed, reason: socket hang up` intermittently instead.

**Comment by enr1424** [comment]
Same issue here.

Node: 20.9.0
firebase-admin: 11.11.0

**Comment by wagerlab** [comment]
Seems it's likely similar to the issue that @zzpreneur is seeing but when I added preferRest: true I started seeing the following error (this time when reading a document although the initial problem I was facing occurred when committing a batch of writes/deletes)

Error: `{"errno":-54,"code":"ECONNRESET","syscall":"read"}`
Message: `Error: read ECONNRESET`

[This issue](https://github.com/firebase/firebase-admin-node/issues/2243) seems to be related as well

**Comment by petrvecera** [comment]
We have lowered all our batch writes to 100 and we didn't get errors on the latest batch processing 🎉 

> Also, may I ask why this issue is not reflected in https://status.cloud.google.com/?

👍 

_Btw be aware that some writes are getting trough with this error. Even though batch writes are suppose to be atomic. Our monitoring based on the logs displays different data than is reality._

**Comment by ehsannas** [comment]
Hi everyone! Thanks again for reporting issues here ❤️
This issue has been resolved as of yesterday evening.
No action is needed on your part: no SDK upgrade needed, no change to your cloud functions needed.

**Comment by jobweegink** [comment]
Hi @ehsannas 
Thanks for fixing it and letting us know.
Can you give a bit more insight in this issue, was it a backend issue?
Is there any way we can prevent or track this in the future?
tbh it caused quite some issues for us, and I think I'm not the only one here.

But, still thanks for fixing it!

**Comment by jessp01** [comment]
I'd like to reiterate @jobweegink's statement. It has greatly inconvenienced my customers (and myself. frankly) and while I acknowledge that s*it will happen, at Google as well as anywhere else, I do feel a technical description of the issue and how it was resolved is reasonable to expect.

**Comment by oyvindholmstad** [comment]
@ehsannas @allspain 

Nothing has changed here. We are still experiencing the issue. I find the error message in the log 24 times the last 12 hours. 

The latest incident happened just an hour ago. 

Gen 1
europe-west1
Node JS 16

**Comment by jferrettiboke** [comment]
Hey guys! 👋

I've also been experiencing the same issue in my client's app, which has been working fine 24/7 for the past three years. In my case, nothing has changed in the codebase for the past three years. So, my conclusion is that this must be something related to Firebase or Google, and not necessarily the business logic of your app.

After extensive research and several attempts, I can confirm that upgrading dependencies to the latest version and using `preferRest: true` works.

Here are the steps:

1. `cd your-project/`
2. `npm install firebase-admin@latest firebase-functions@latest`
3. `npm install -g firebase-tools@latest`
4. Update your Firestore settings and add `preferRest: true` (see the code below).
5. Deploy your functions again.

```js
const admin = require("firebase-admin");

const firestore = admin.firestore();

firestore.settings({ preferRest: true });

// Use Firestore as usual
```

Depending on what your previous versions were before upgrading, you could encounter some breaking changes. Make sure to read the changelogs first and adapt your project as needed.

If you run into issues when deploying your functions, I recommend using debug mode: `firebase deploy --only functions --debug`. That way, you will know what's happening.

Please don't take this as the definitive solution. This is what worked for me, and that's why I'm sharing it. It might or might not work for you. If it doesn't work, feel free to ask. I'll do my best to provide a quick response.

Happy coding, buddies! 👩🏻‍💻

**Comment by ciriousjoker** [comment]
@ehsannas 
Same for us. The error is still appearing (last 2 hours ago).

**Comment by oyvindholmstad** [comment]
@ehsannas @allspain This is still happening. Please re-open the issue.

**Comment by ehsannas** [comment]
Hi @ciriousjoker @oyvindholmstad . This was not an SDK issue, and is believed to be fully addressed. If you are still experiencing an issue, I'd encourage you to reach out to Google Cloud Support or Firebase Support.

**Comment by garveychan** [comment]
Hi all, just wanted to post about my experience with this error in case anyone else was still having this issue after trying all of the above fixes.

Essentially, my cloud function was set up to execute a series of smaller async functions that each performed a `firestore.get()` and pushed a `doc.update()` to a promise array that was returned in a `Promise.all()` out of the overall cloud function.

I was encountering this error because I wasn't properly **awaiting** each of the smaller async functions so the `firestore.get()` was being invoked **AFTER** the function execution was complete.

As soon as I awaited them properly, my functions ran flawlessly.

tldr - check your promises.

Hope this helps anyone having the same problem.

**Comment by jobweegink** [comment]
> Hi @ciriousjoker @oyvindholmstad . This was not an SDK issue, and is believed to be fully addressed. If you are still experiencing an issue, I'd encourage you to reach out to Google Cloud Support or Firebase Support.

We also still receive this error while nothing has changed, we didn't redeploy anything since a few months, but it came out of nowhere, are you sure you fixed this issue for all Firestore regions?

And also about my other comment, can you please get back to that as well, I feel like it's being ignored even though this had and has a great impact on us.

**Comment by ciriousjoker** [comment]
@jobweegink good Point about the regions.

We're using europe-west1, what about you, @oyvindholmstad & @jobweegink?

**Comment by oyvindholmstad** [comment]
@ciriousjoker europe-west1 here as well!

**Comment by jobweegink** [comment]
> @jobweegink good Point about the regions.
> 
> We're using europe-west1, what about you, @oyvindholmstad & @jobweegink?

Europe-west for me

**Comment by nikoSchoinas** [comment]
Hello, the issue remains for us too without having deployed anything new. We also use **europe-west1**. More specifically:
Gen 2
Node 16
firebase-admin 11.10.0
firebase-functions 4.4.0

**Comment by loicsalzmann** [comment]
Helpppppp please 😱 My app with 30k users playing every day is totally broke... Got this random error hundreds times a day on several functions...... Error: 13 INTERNAL: Received RST_STREAM with code 2

Please help !

**Comment by ciriousjoker** [comment]
@loicsalzmann I recommend contacting the Firebase support about this, they can escalate this much more than comments on a closed issue can. Especially if you can provide them with a reproducible example (MCVE) and the node, firebase-functions, 1st/2nd gen functions etc. versions you're using.

**Comment by oyvindholmstad** [comment]
For what it's worth, I have contacted support, and they have escalated the issue to the engineering team. I have been promised a response before 10th November 2023, 10:00 PM IST. We still see this daily.

**Comment by loicsalzmann** [comment]
> For what it's worth, I have contacted support, and they have escalated the issue to the engineering team. I have been promised a response before 10th November 2023, 10:00 PM IST. We still see this daily.

Please Keep posted :-)

**Comment by HansaExport** [comment]
Please we need a fix for this! The workaround to reinit the firebase/db on every functions-call is no good solution...

region: europe-west1

**Comment by oyvindholmstad** [comment]
Got an update from support on friday:

"As informed earlier, we have reported your issue concern to the Engineering team and many users have reported that issue also. Please be assured that the Engineering team has started working on the issue and I’m actively working with them to get updates on your issue. I will reach out to you as soon as I have an update from the Engineering team but no later than (2 business days) 14th November 2023, 10:00 PM IST."

**Comment by loicsalzmann** [comment]
It seems that the problem is fixed on my end; I haven't encountered any errors anymore. Fortunately, thank God. 🙏🏼

**Comment by HansaExport** [comment]
> Got an update from support on friday:
> 
> "As informed earlier, we have reported your issue concern to the Engineering team and many users have reported that issue also. Please be assured that the Engineering team has started working on the issue and I’m actively working with them to get updates on your issue. I will reach out to you as soon as I have an update from the Engineering team but no later than (2 business days) 14th November 2023, 10:00 PM IST."

Is there an update?

**Comment by oyvindholmstad** [comment]
@loicsalzmann Good to hear. Problem persists on our end, unfortunately 😩 

@HansaExport Nothing new. They keep pushing the date forward:

"Hello,

Thank you for your patience.

I would like to inform you that I'm still waiting for an update from the Product Engineering Team. As informed earlier many users have reported that issue also and Please be assured that the Engineering team has started working on the issue and I’m actively working with them to get updates on your issue. I will reach out to you as soon as I have an update from the Engineering team but no later than 17th November 2023, 10:00 PM IST.

I would like to set the right expectation that the issue troubleshooting may take a while to narrow down the root cause of this. I appreciate your understanding and cooperation in this matter."

**Comment by oyvindholmstad** [comment]
Got an update from support today:

> I received an update from the Product Engineering team regarding the ETA. As per their update we have an internal potential mitigation that will be deployed on the week of December 4th and is expected to take effective on December 4th or 5th. Please be informed that we are working with high priority on this issue and I will keep you updated actively.
> I appreciate your patience as we continue to investigate this issue. Meanwhile, if you have any further concerns or queries, please feel free to reach out to me, I will be happy to assist.

**Comment by jobweegink** [comment]
Thanks for sharing!
That doesn't sound as high priority to me but okay.
But what they are basically saying is that it is a back end issue?

**Comment by oyvindholmstad** [comment]
@jobweegink Correct, they have confirmed that the issue is on the backend.

**Comment by oyvindholmstad** [comment]
New update from support:

> As a follow up of the case I would like to inform you that the migration has been initiated and it is in progress now. It will be effective from December 5th. Please be informed that we are working with high priority on this issue and I will keep you updated actively.

**Comment by uafrontender** [comment]
I develop google cloud function locally with `@google-cloud/functions-framework` and `@google-cloud/aiplatform`

Got same issue today after calling `await predictionServiceClient.predict(request)`

![image](https://github.com/firebase/firebase-admin-node/assets/1360242/d7765a70-c35f-4a88-8da6-aa4f38319c1d)

**Comment by stanislav-savchuk** [comment]
I still experience the issue described here. Is there a fix for it?
Would be glad for any type of help!
