### ISSUE TITLE
13.0.0 can't be used with the latest firebase-functions release (npm error: Conflicting peer dependency)

### ISSUE THREAD

**Issue by arnab** [firebase/firebase-admin-node#2772]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Mac OSX 15.1
  * Firebase SDK version: 12
  * Firebase Product: Functions & admin
  * Node.js version: 18 (18.16)
  * NPM version: 9.5.1

### [REQUIRED] Step 3: Describe the problem

* `firebase-admin` has a new `13.0.0` release: https://www.npmjs.com/package/firebase-admin
* But if you try to use it with `firebase-functions` (latest release: `6.1.0`), you get an npm error: https://www.npmjs.com/package/firebase-functions?activeTab=readme

```
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: firebase-functions@[6](https://github.com/orcalabs-dev/podcast-directory-management-tools/actions/runs/11891283442/job/33131715188?pr=161#step:5:7).1.0
npm error Found: firebase-admin@13.0.0
npm error node_modules/firebase-admin
npm error   firebase-admin@"^13.0.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer firebase-admin@"^11.10.0 || ^12.0.0" from firebase-functions@6.1.0
npm error node_modules/firebase-functions
npm error   firebase-functions@"^6.1.0" from the root project
npm error   peer firebase-functions@">=4.9.0" from firebase-functions-test@3.3.0
npm error   node_modules/firebase-functions-test
npm error     dev firebase-functions-test@"^3.3.0" from the root project
npm error
npm error Conflicting peer dependency: firebase-admin@12.[7](https://github.com/orcalabs-dev/podcast-directory-management-tools/actions/runs/11891283442/job/33131715188?pr=161#step:5:8).0
npm error node_modules/firebase-admin
npm error   peer firebase-admin@"^11.10.0 || ^12.0.0" from firebase-functions@6.1.0
npm error   node_modules/firebase-functions
npm error     firebase-functions@"^6.1.0" from the root project
npm error     peer firebase-functions@">=4.[9](https://github.com/orcalabs-dev/podcast-directory-management-tools/actions/runs/11891283442/job/33131715188?pr=161#step:5:10).0" from firebase-functions-test@3.3.0
npm error     node_modules/firebase-functions-test
npm error       dev firebase-functions-test@"^3.3.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

* This is because, `firebase-functions` has an explicit peer dependency on previous version of `firebase-admin`: 
  - https://github.com/firebase/firebase-functions/blob/cd88163f687a83d541c6a4391c3cf96b81960b2e/package.json#L322

#### Steps to reproduce:

* Add dependency on the latest `firebase-admin` and `firebase-functions`
* Run `npm install`

**Comment by taeold** [comment]
This was fixed in latest patch release!

https://github.com/firebase/firebase-functions/releases/tag/v6.1.1

Sorry for the delay.

**Comment by arnab** [comment]
Right, this is not fixed yet, @taeold (thanks @simeon9696):

Using the latest releases:

```
  "dependencies": {
    // ... more deps... 
    "firebase-admin": "^13.0.1",
    "firebase-functions": "^6.1.1",
  },    
  "devDependencies": {
    // ... more deps... 
    "firebase-functions-test": "^3.3.0",
  },    
```

This is still failing:

```
➜  functions git:(dependabot/npm_and_yarn/functions/firebase-admin-13.0.1) npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: firebase-functions-test@3.3.0
npm ERR! Found: firebase-admin@13.0.1
npm ERR! node_modules/firebase-admin
npm ERR!   firebase-admin@"^13.0.1" from the root project
npm ERR!   peer firebase-admin@"^11.10.0 || ^12.0.0 || ^13.0.0" from firebase-functions@6.1.1
npm ERR!   node_modules/firebase-functions
npm ERR!     firebase-functions@"^6.1.1" from the root project
npm ERR!     peer firebase-functions@">=4.9.0" from firebase-functions-test@3.3.0
npm ERR!     node_modules/firebase-functions-test
npm ERR!       dev firebase-functions-test@"^3.3.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer firebase-admin@"^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0" from firebase-functions-test@3.3.0
npm ERR! node_modules/firebase-functions-test
npm ERR!   dev firebase-functions-test@"^3.3.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: firebase-admin@12.7.0
npm ERR! node_modules/firebase-admin
npm ERR!   peer firebase-admin@"^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0" from firebase-functions-test@3.3.0
npm ERR!   node_modules/firebase-functions-test
npm ERR!     dev firebase-functions-test@"^3.3.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Looks like `firebase-functions-test` needs to be fixed too.

**And perhaps even more importantly, there needs to be a process (or not explicit major version dependency checks in `firebase-functions` and `firebase-functions-test`), so that this does not keep happening with every major release** (see my comment above: https://github.com/firebase/firebase-admin-node/issues/2772#issuecomment-2483842249).

**Comment by Trashpants** [comment]
not exactly a fix but a work around until this gets sorted for me was:

```
"overrides": {
  "firebase-functions-test": {
	  "firebase-admin": "^13.0.0"
  },
  "tough-cookie": "4.1.3"
},
```

not sure if tough-cookie is needed for everyone but something to do with @types/request had an issue with it for me too

**Comment by simeon9696** [comment]
@taeold can this be fixed soon?

**Comment by Simon-JB** [comment]
I still have this error when trying to deploy a cloud function. I tried with multiple versions of firebase-functions and firebase-admin and never got it to work.

While resolving: firebase-functions@6.1.2
Found: firebase-admin@10.3.0
  node_modules/firebase-admin
  firebase-admin@"^10.3.0" from the root project
   peer firebase-admin@">=6.0.0" from firebase-functions-test@0.2.3
   node_modules/firebase-functions-test
     dev firebase-functions-test@"^0.2.0" from the root project
 
Could not resolve dependency:
 peer firebase-admin@"^11.10.0 || ^12.0.0 || ^13.0.0" from firebase-functions@6.1.2
 node_modules/firebase-functions
   firebase-functions@"^6.1.2" from the root project
   peer firebase-functions@">=2.0.0" from firebase-functions-test@0.2.3
   node_modules/firebase-functions-test
     dev firebase-functions-test@"^0.2.0" from the root project
 
 Conflicting peer dependency: firebase-admin@13.0.2
 node_modules/firebase-admin
   peer firebase-admin@"^11.10.0 || ^12.0.0 || ^13.0.0" from firebase-functions@6.1.2
   node_modules/firebase-functions
     firebase-functions@"^6.1.2" from the root project
     peer firebase-functions@">=2.0.0" from firebase-functions-test@0.2.3
     node_modules/firebase-functions-test
       dev firebase-functions-test@"^0.2.0" from the root project

**Comment by lahirumaramba** [comment]
Looks like this issue is fixed in https://github.com/firebase/firebase-functions-test/pull/252
@taeold and I will discuss an approach to setting up a workflow to avoid this in the future. Thanks folks!
