### ISSUE TITLE
Issue in getRulesJSON() firebase-admin SDK 8.7.0

### ISSUE THREAD

**Issue by purusho95** [firebase/firebase-admin-node#747]
Error : { code: 'database/internal-error',
     message:
      'Error while accessing security rules: Unexpected server error' }

**Comment by hiranya911** [comment]
Doesn't reproduce. You will have to provide more details -- environment information, sample code etc.

**Comment by purusho95** [comment]
Sure.
Node v10.16.3
Mac OS 10.14.1
firebase-admin : 8.9.0
firebase-functions : 3.1.0

Sample code

admin.database().getRulesJSON().then( json =>{
  console.log(json);
}).catch( err => {
  console.log('Error message : '+err.message)
})

**Comment by hiranya911** [comment]
Works fine as far as I can tell. Here's my full test code:

```
const admin = require('firebase-admin');

admin.initializeApp({
    credential: admin.credential.applicationDefault(),
    databaseURL: 'https://<project_id>.firebaseio.com/',
});

admin.database().getRulesJSON().then( json =>{
    console.log(json);
}).catch( err => {
    console.log('Error message : '+err.message)
})
```

And I get the output as expected:

```
{ rules: { '.read': false, '.write': false } }
```

It doesn't look like there's any SDK-level bug here. Most likely a configuration issue on your end. Make sure your credential (service account) and the database URL are from the same Firebase project. If the problem occurs consistently, and all the configuration looks correct, please raise an issue at https://firebase.google.com/support so we can look at your specific database/project and see why it would return an "Unexpected server error".

**Comment by rhodgkins** [comment]
@hiranya911 I'm getting the same error, I've extracted the request via debugging and turned it into a cURL and get the same error there.

Works:

```
curl -H 'authorization: Bearer <authToken>' https://<db-name>.firebaseio.com/.settings/rules.json
<rules>
```

```
curl -H 'authorization: Bearer <authToken>' https://<db-name>.firebaseio.com/.settings/rules.json?format=strict
{
  "error" : "Unexpected server error"
}
```

Seems to be the server can't create JSON rules.

**Comment by hiranya911** [comment]
What does your rules look like in the console?

**Comment by rhodgkins** [comment]
After much debugging I found this is the smallest use case to reproduce the issue:

```
{	
   "rules": {
      ".read": false,
   }
}
```

It's obvious now that we had a bad `,` in our rules but the rules editor in the console hadn't picked it up!
We've corrected this now and it `getRulesJSON` works so I guess the issue is more so in the rules editor...

**Comment by hiranya911** [comment]
Thanks @rhodgkins for the update. I'm going to file a bug for this for our RTDB team. I think both the console and the Rules REST API should be able to handle this case gracefully.

**Comment by rek** [comment]
This is still happening for me too. Glad this issue is here that helped me solve it quickly though. Is there a link to a story for the RTDB team we can follow?

**Comment by RandomToni** [comment]
Hello @hiranya911, is there any updates on this issue? Thank you.
